package com.plunex.emilokan.modules.event;


import com.plunex.emilokan.modules.subscription.Subscription;
import com.plunex.emilokan.modules.user.User;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.lang.NonNull;

import java.util.Collection;
import java.util.UUID;


@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table
public class Event {

    /// Barcodes will be generated by iD
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @ManyToOne()
    @JoinColumn(name = "manager_id")
    private User user;

    @NonNull
    @Column
    private String title;

    @NonNull
    @Column
    private String description;

    @OneToMany(mappedBy = "event")
    private Collection<Subscription> subscribers;


}
